{{- $secret := lookup "v1" "Secret" .Release.Namespace "hasura.plural-hasura.credentials.postgresql.acid.zalan.do" }}
{{- if $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: hasura.plural-hasura.credentials.postgresql.acid.zalan.do
  labels:
  {{- include "hasura.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.hasura.pgClient.external.username | default $secret.data.username }}
  password: {{ .Values.hasura.pgClient.external.password | default $secret.data.password }}
{{- end }}
