# Default values for hasura.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  ingressClassName: nginx
  host: ''
  annotations:
    kubernetes.io/tls-acme: "true"
    # Extend timeout to allow long running queries.
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/session-cookie-path: /v1/graphql

hasura:
  enableConsole: 'true'
  consoleAssetsDir: /srv/console-assets
  extraEnvVarsCM:
    PGSSLMODE: require
  ingress:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m

postgres:
  enabled: true
  team: plural
  user: hasura
  dbName: hasura
  ownerChart: hasura
  password: CHANGEME
  infix: ""
